version: '3.9'
services:
  fileparser:
    build: ./
    environment:
      - DB_URL=postgresql://postgres:admin@db:5432/fileparser  
  db:
    image: postgres:12-alpine
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=fileparser
volumes: 
  pgdata:  
